#rabbitmq server basic config
rabbitmq:
  lw:
    address: 127.0.0.1:5672
    username: liuwei
    password: 123
    vhost: test

spring:
  redis:
    database: 10
    host: 172.24.133.35
    port: 20005
    timeout: 6000   # 连接超时时间（毫秒）
    password: myredis
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

#mongodb server configuration
  data:
    mongodb:
      server:
        address: 127.0.0.1:27017
        username:
        password:
        dbname: test
